#!/bin/sh

YELLOW='\033[1;33m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color


sec=${1:-2}
lines=${2:-20}
clear_count=${3:-10}

if [ $# -lt 3 ]; then
    printf "${YELLOW}Warning:${NC} Not enough arguments, "
    printf "using defaults where possible.\n"
    printf "${YELLOW}Arguments:${NC} login-radar $sec(sec) "
    printf "$lines(lines) $clear_count(clear count)\n\n"
    sleep 3
fi

counter=0
while true; do

    if [ $counter -eq $clear_count ]; then
        clear
        counter=0
    fi

    counter=$((counter + 1))
    printf "[Clear count ${YELLOW}${counter}/${clear_count}${NC}]\n"

    wtmpdb last -n $lines -Sa

    printf "\nPress ${LIGHT_RED}'Ctrl+C'${NC} to exit: "
    sleep $sec

    printf "\033[2K" # Erase the whole line
    printf "\r" # Return carriage
done
